# Site settings
title: Joe's Blog
subtitle: "Journal of Joe"
email: your-email@domain.com
description: "A blog about all the things I'm learning and getting confused by"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: "Joe_g_Robertson"
github_username:  "joe-robertson"
instagram_username: "jgrsparks"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
